// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;

namespace IdentityAuthWithDBFirst.Data;

public partial class AspNetUserLogin: IdentityUserLogin<string>
{
}